### ISSUE TITLE
Not working with Debian "inetutils-ping"

### ISSUE THREAD

**Issue by ceinmart** [famzah/ping-multi-ext#2]
Hi , 

Just installed your ping-multi-ext , however it not working and have no option to be more verbose to try understand why : 

![image](https://github.com/famzah/ping-multi-ext/assets/7062410/83cd02b1-0410-464c-89a9-4d26537c40ab)

**Comment by ceinmart** [comment]
Just saw now : 

![image](https://github.com/famzah/ping-multi-ext/assets/7062410/f55cb32a-0ad5-4e97-a592-565f81807cde)


I'm running on debian , the ping is from inetutils.. 
-O is a option of iputils...

**Comment by ceinmart** [comment]
solved... 
just replaced the package from inetutils-ping to iputils-ping

**Comment by famzah** [comment]
Thank you for debugging this.
