### ISSUE TITLE
add ability to ping all usable addresses in subnet

### ISSUE THREAD

**Issue by siguroot** [famzah/ping-multi-ext#4]
Another idea (and something that would be very useful in my professional capacity) would be to able to provide an argument that accepts a cidr address which in turn will start pinging all usable addresses in a subnet.  I currently do this with fping, but I much prefer this tool.  

ex:

fping -g 10.0.0.0/27 --loop

What are your thoughts?  I could attempt to implement this and put in a pull request if you like.

**Comment by siguroot** [comment]
I took a crack at it: https://github.com/siguroot/ping-multi-ext/tree/cidr

what do you think?

**Comment by famzah** [comment]
Sounds good. A few questions before we go into implementation details:
- Shouldn't there be a limit?  What if someone tries by mistake ``1.0.0.0/12``? I'm wondering if this limit should be for "cidr" or generally for all hosts that we're about to ping. Something like "-L,--count-limit" with help "a total limit of all hosts to work with" (default: 256?)
- I think we should directly recognize CIDR patterns in the regular hostname arguments and expand it to a list. No need for a new command-line argument. This can be done at the end when the "hosts" list is already populated by the command-line arguments and any "-f" files.
- "ping_multi: -g works only with IPv4 addresses". We call the regular "ping" command and it should work with both IPv4 and IPv6.

What do you think?

**Comment by siguroot** [comment]
> * Shouldn't there be a limit?  What if someone tries by mistake `1.0.0.0/12`? I'm wondering if this limit should be for "cidr" or generally for all hosts that we're about to ping. Something like "-L,--count-limit" with help "a total limit of all hosts to work with" (default: 256?)

Agreed.  Giving a argument (-L) to override if /12 wasn't a mistake, is a nice touch.  Default of 256 seems reasonable.  

> * I think we should directly recognize CIDR patterns in the regular hostname arguments and expand it to a list. No need for a new command-line argument. This can be done at the end when the "hosts" list is already populated by the command-line arguments and any "-f" files.

You are correct! You could match on '/' or something like that.  

> * "ping_multi: -g works only with IPv4 addresses". We call the regular "ping" command and it should work with both IPv4 and IPv6.
> 

Definitely COULD make it dual stacked, but given the vast size of IPv6 and most prefix masks being set to /64, the host limit will likely always be enforced.  Most you could do would be a /120 (without overriding).  I doubt ping can scale to 2^64 hosts bits!  But then again a targeted subset of a subnet could be useful.  It would have to be very deliberate to be useful imo.  


> What do you think?

I think this is great.  Love that I'm getting any input at all into a tool I use on the daily.

**Comment by famzah** [comment]
Please test if the new feature functions as expected for you. You need to checkout "ping-multi" from GitHub directly because I haven't published the new version to PyPi, yet:

```Bash
git clone https://github.com/famzah/ping-multi-ext.git
python3 -m venv ping-multi-ext
cd ping-multi-ext/
. bin/activate
pip3 install blessings curtsies
./ping-multi

**Comment by siguroot** [comment]
How picky did you want to be on validity of the cidr provided?  Sometimes people enter a network address whereas a host bit is set.  I would recommend we do one of the following:

*  output an error if host bit are set ex:  ValueError: 10.0.0.1/30 has host bits set
or
* set strict boolean to False in IPv4Network - `net = ipaddress.IPv4Network(host_input,strict=False)`

The performance of counting hosts from an unrealistic cidr (ex: 10.0.0.0/8) takes a while. Might want to utilise `ipaddress.IPv4Network('10.0.0.0/8').num_addresses` to get a count to evaluate against the max hosts?  

Thoughts?

**Comment by famzah** [comment]
If a CIDR isn't recognized as such, the command-line option ``--cidr-debug`` is there to explain why:
```
$ ./ping-multi 10.0.0.1/30 --cidr-debug
usage: ping-multi [-h] [--version] [--hosts-max-width HOSTS_MAX_WIDTH] [-s {Last,Loss%,Avg,Min,Max,StDev,RX_cnt,TX_cnt,XX_cnt}] [-f FILE]
                  [-W SECS] [-i SECS] [-L COUNT_LIMIT] [-C]
                  [host ...]
ping-multi: error: argument "10.0.0.1/30": 10.0.0.1/30 has host bits set
```

But I think that `strict = false` is the right way to go!

--

It's true that it gets slow for a very big CIDR. I will compare each CIDR expansion ``.num_addresses`` against the value of ``--count-limit``.

**Comment by famzah** [comment]
I've implemented what we discussed. Please test and report if everything functions as expected.

**Comment by famzah** [comment]
I'm wondering if ``--cidr-debug`` shouldn't be "on" by default? Can you find a use-case where you want it off?

What errors can you reproduce for an invalid CIDR? I came up only with the following and I think users should get an error immediately:
```
./ping-multi 192.168.590.500/25 --cidr-debug

ping-multi: error: argument "192.168.590.500/25": Octet 590 (> 255) not permitted in '192.168.590.500'
```

Having ``strict = false`` may have made ``--cidr-debug`` obsolete and we should just turn it "on" by default without an option to turn it off?

**Comment by siguroot** [comment]
I completely agree, we should just leave it on by default.  As for errors I can reproduce, I can think of many things people might do that are syntax related.  But I think that is out of scope.  As for data entered with proper cidr syntax, ipaddress library and your scripts existing validation is sufficient, imo.

**Comment by famzah** [comment]
All done. You can upgrade using ``pip``.

Thank you for contributing to "ping-multi"!
